# GitLab API access config
gitlab:
  # You can also set in your environment GITLAB_URL
  url: http://10.150.12.49
  # You can also set in your environment GITLAB_TOKEN
  token: "33xQsSw59TvY95NHzZK6"
  # GitLab API version. As of now only 4 is supported.
  api_version: 4

common_settings:
  # common settings for ALL projects in ALL groups

  secret_variables:
    # this name is not actually used, it's just for you
    a_secret_you_want_to_add_to_all_projects_in_your_gitlab_instance:
      key: A_VERY_COMMONLY_USED_PASSWORD
      value: "ThisIsAVerySecretPassword"
  
  group_secret_variables:
    # this name is not actually used, it's just for you
    a_secret_you_want_to_add_to_all_projects_in_your_gitlab_instance:
      key: A_VERY_COMMONLY_USED_SECRET
      value: "ThisIsAVerySecretPassword"
      variable_type: env_var #or file
      protected: false #

group_settings:
  # settings for ALL projects in 'my_group' group
  "secondgroup":

    group_secret_variables:
      # this name is not actually used, it's just for you
      a_secret_:
        key: A_VERY_COMMONLY_USED_VAR
        value: "ThisIsAVerySecretPassword"
        variable_type: env_var #or file
        protected: false #
      # this name is not actually used, it's just for you
      a_secret_file:
        key: A_VERY_COMMONLY_USED_FILE
        value: "ThisIsAVerySecretPassword"
        variable_type: file #or file
        protected: false #
      # this name is not actually used, it's just for you
      another_secret_file:
        key: A_VERY_COMMONLY_USED_FILE
        value: |
          ThisIsAVerySecretPassword
          with multiline!
        variable_type: file #or file
        protected: false #